### ISSUE TITLE
Secret management

### ISSUE THREAD

**Issue by maximousblk** [charmbracelet/charm#14]
I was looking for a way to store my secrets recently, and a common occurrence among the suggestions and solutions was to encrypt each secret using another key and store the encrypted keys in a secure place where only you have access to it (automated solutions would handle the encrypting and storing for you). but the problem with those is, the secrets are not synced across all my devices. and if I loose the access to my device or the "master" key, I loose all my secrets.

Today this idea popped in my head: If charm can securely store and sync my markdown notes across my devices, why can it not store my secrets? So the immediate solution would be to create a markdown file with all the secrets in it but that's not really a solution at all imo.

So I propose the following feature request:

```sh

charm secrets                                     # list all secrets' names (similar to `charm keys`)

charm secrets add SECRET_NAME < cat secret_file   # add a secret (similar to `glow stash`)

charm secrets get SECRET_NAME                     # get the value of the secret

charm secrets remove SECRET_NAME                  # get the value of the secret

```

this would allow things like

```sh

some_tool --passphrase $(charm secrets get SECRET_NAME)

```

command name and format can change

**Comment by toby** [comment]
Thanks for this, it's a great idea and we've been thinking something similar.

**Comment by maximousblk** [comment]
Any updates on this?

**Comment by toby** [comment]
Actually, this is great timing! We're very close to launching some stuff that intersects with this issue. Would you be interested in helping private beta test? Here's an invite to our Slack to help get started:

https://join.slack.com/t/charmbracelet/shared_invite/zt-tseeir8y-psT75Vfvx14MrnRKU~l9mg

**Comment by maximousblk** [comment]
I would love to test it out, thanks!

**Comment by toby** [comment]
Hi @maximousblk! This should now be doable with `charm kv` thank you so much for all of the support!
