### ISSUE TITLE
Any tests, any tests?

### ISSUE THREAD

**Issue by tauraamui** [charmbracelet/charm#193]
Hello, I was wondering if there was any desire for more tests to be written for existing functionality, and if so I am excited to offer up my best efforts to help! Please let me know where the most priority areas would be. :)

**Comment by bashbunni** [comment]
Replied in [Discord](https://charm.sh/chat), but for context for GH people:
> hey, we are currently working in something new... so this will soon be changed a lot, probably not worth looking into it just now.
> thanks for wanting to help though, its greatly appreciated! If you're into tests, there are some more projects that could use more tests, and would love to hear what you think in [this pr](https://github.com/charmbracelet/bubbletea/pull/352) too!
