### ISSUE TITLE
Self-Hosting: CHARM_HOST Env uses port 35353 instead of 443?

### ISSUE THREAD

**Issue by azoller1** [charmbracelet/charm#209]
Hello, I have charm running in a docker container with `charm.mydomain.net` reverse proxied to the http port 35353 from the container with caddy.

Everything looks good with the container/host. Also have `CHARM_SERVER_PUBLIC_URL=charm.mydomain.net` set.

So, when using skate on a different host with `CHARM_HOST=https://charm.mydomain.net`, it seems to be using 35353 instead of 443, which I would assume it would use by default?
```
$ skate list
Error: authentication failed: dial tcp: address https://charm.mydomain.net:35353: too many colons in address
```

Is there possibly a `PORT` env I am missing? Also, I am assuming skate uses http and not ssh correct?

**Comment by bashbunni** [comment]
Hey @azoller1 I think you're looking for the `CHARM_SERVER_SSH_PORT`. You can see all the env variables for Charm in [this](https://github.com/charmbracelet/charm#self-hosting) section of the readme. Skate uses SSH by default, not HTTP. The auth is done with SSH keys, so we generally use SSH > HTTP. 

Hope that helps!!

**Comment by richard-kramer** [comment]
I don't think, that answers the question, does it?

The `CHARM_SERVER_SSH_PORT` variable ist a server setting, but the problem ist pointing the **client** to another port than `35353`. For example, when running skate behind a reverse proxy, which accepts https connections on `443`.

The mentioned setting simply tells the server (potentially inside the docker container) to listen on another port for ssh connections, which doesn't affect the client at all.

Can we please reopen this? Or are there some hidden settings, that already exist?
