### ISSUE TITLE
Document Charm Cloud

### ISSUE THREAD

**Issue by mxplusb** [charmbracelet/charm#229]
I looked all over your website and through the varying repos, but I couldn't find any documentation on the Charm Cloud. I understand it's a hosted version of this code base, but there are open questions I have around data security, data governance, encryption, etc. Can you please document the Charm Cloud features, security, and operational model?

**Comment by bashbunni** [comment]
Hey @mxplusb! I just took a look and it seems we haven't updated that section of our README to include much information on how that works behind the scenes. I'm going to draft a PR to update the docs. In the meantime if you have any specific questions you'd like answered, please let us know so we can include that as well in the documentation.

**Comment by mxplusb** [comment]
I'm mostly curious about data security as a starting point :)

**Comment by bashbunni** [comment]
@mxplusb you can see all of our info on encryption at https://github.com/charmbracelet/charm/tree/main/crypt
As you can see it's  end-to-end encrypted (it gets encrypted on your machine before anything is pushed to the server). Let us know if you feel there's anything missing from that info and we'll happily re-open this issue!

**Comment by mxplusb** [comment]
I read up on #231 and the link you shared, lgtm! Thank you :)
