### ISSUE TITLE
Charm embeddable chat

### ISSUE THREAD

**Issue by FBDev64** [charmbracelet/charm#283]
A platform that uses Charm Accounts to chat, written in bash, that we can embed in our Apps.

**Comment by dezren39** [comment]
personally, i would love this. i think the biggest issue is there is no (easy) way to transfer data between accounts. the way the encryption works makes this difficult. it might be better a bit more generalized as streaming capabilities and/or file sharing capabilities with a chat app that uses the stream capabilities. this might put a bit of load on the charm server without thinking through the right tech to handle the data. might need acl of some kind for fs or stream, something like public/unlisted/private and private is a list of public keys that can connect. the way the users work now there isn't much of an idea of groups, especially user created groups, so a list of public keys attached to a specific fs or stream would be closest you could get without implementing.. more.
