### ISSUE TITLE
bug(windows): backup recursively creates blank tarballs

### ISSUE THREAD

**Issue by maximousblk** [charmbracelet/charm#4]
When I backup the keys on windows, the backup tar file contains a series of blank tarballs

![image](https://user-images.githubusercontent.com/28438021/96404665-1c0bdb00-11f9-11eb-94f9-8f35aa328387.png)

**Comment by maximousblk** [comment]
I think this was fixed by https://github.com/charmbracelet/charm/commit/b28c93f6cd152acc85e0ddb64bacf918c63279cc too?

![image](https://user-images.githubusercontent.com/28438021/101616303-3a41ca80-3a35-11eb-9077-16ffdd4bf3d6.png)

**Comment by meowgorithm** [comment]
You're correct. I can confirm this is fixed on Windows.

The `\\` is a bit odd. Curious that we don't see that on unix-like systems.
