### ISSUE TITLE
Charm keys import to the wrong directory

### ISSUE THREAD

**Issue by benthillerkus** [charmbracelet/charm#5]
As I can't run both OS at the same time, I can't complete the verification process.
I've tried backing up and loading the backup on the other OS, but that didn't work either.

**Comment by toby** [comment]
Hi! It _should_ work if you `charm backup-keys` then take that file and `charm import-keys charm-keys-backup.tar`. When you do that, do you get an error?

We plan to add additional linking methods as well.

**Comment by benthillerkus** [comment]
Yeah, that's what I've tried. I just noticed, that when I run `charm keys` it won't actually show me all keys, but only the one in use. After I had deleted that one, I think it picked the one I must've imported earlier. `glow stash` still doesn't show the one synched markdowns though.

I think the `import-keys` command might be broken:
![image](https://user-images.githubusercontent.com/29630575/96632587-35f00f80-1318-11eb-8494-ea7844d89f83.png)

**Comment by benthillerkus** [comment]
Deleting the files from 19:01 renaming the other ones worked.
I think there are two problems:
1. It made a new directory called charm
2. It de-archived these files neither into the main directoy, nor into the subdirectory, but instead just named them `charm\charm_rsa`.

**Comment by toby** [comment]
Good find, you're correct that the import should not create a sub directory. We'll fix this.

**Comment by meowgorithm** [comment]
This should be fixed now. @benthillerkus, thanks for the report and do let us know if you have any more trouble with this.

**Comment by meowgorithm** [comment]
This fix is now available in the current release.
