### ISSUE TITLE
readme a little light on authentication 

### ISSUE THREAD

**Issue by trashhalo** [charmbracelet/charm#6]
was curious what I could do with charm and was looking around. there is mention of seamless user auth. and I see jwt stuff in the godoc. but how to use it is alittle unclear. maybe add more docs to readme or add links to read more about how to use charm in this way.

# the open questions I have

1. How do I establish identity on a machine?
2. Once established what do I do with that identity? Can I use it as auth on a backend system? If so, how?
3. How do I migrate that identity from one machine to another?

**Comment by trashhalo** [comment]
I pulled down the charm app. And it's a little more clear. I see that launching charm create a key and there is a link machine and backup.

This all make sense. I think I'm just confused about charm the library. I think the authentication the readme talks about now is purely auth between the library and charms servers.

Does that mean the reason I would use charm library is to make calls in my app to the charm backend? Like to stash a markdown file.

**Comment by toby** [comment]
Hi @trashhalo, all the docs are updated with the new rewrite. Let us know if anything is still unclear, but I'm going to close this for now as it referenced the old `charm`.
