### ISSUE TITLE
go get ...charm blows up on my machine

### ISSUE THREAD

**Issue by trashhalo** [charmbracelet/charm#7]
```shell
➜  dev go get github.com/charmbracelet/charm/cmd/charm
# github.com/charmbracelet/charm/ui/username
../go/src/github.com/charmbracelet/charm/ui/username/username.go:130:20: too many arguments in call to textinput.Blink
	have (textinput.Model)
	want ()
../go/src/github.com/charmbracelet/charm/ui/username/username.go:130:20: cannot use textinput.Blink(m.input) (type tea.Msg) as type tea.Cmd in return argument: need type assertion
../go/src/github.com/charmbracelet/charm/ui/username/username.go:194:20: undefined: textinput.Update
../go/src/github.com/charmbracelet/charm/ui/username/username.go:234:18: undefined: textinput.Update
../go/src/github.com/charmbracelet/charm/ui/username/username.go:243:7: undefined: textinput.View
```

➜  dev go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/stephen/.cache/go-build"
GOENV="/home/stephen/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/stephen/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/stephen/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/stephen/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build142608877=/tmp/go-build -gno-record-gcc-switches"

**Comment by meowgorithm** [comment]
Hey, there! You're seeing this because Go is fetching the source code without module support. If you set `export GO111MODULES=1` and then run the command it should be fine. I believe this behavior will go away in Go 2.

Alternatively you can clone the repo and build the command that way. Or, if you’re on a Mac: `brew tap charmbracelet/tap && brew install charmbracelet/tap/charm`.

I'll update the installation instructions accordingly.

**Comment by muesli** [comment]
It's actually coming in Go 1.16, luckily. About time they cleaned that up.
