### ISSUE TITLE
Can't git it

### ISSUE THREAD

**Issue by fredguth** [charmbracelet/charm#72]
```
> ssh git.charm.sh                  

z4h: failed to upload bootstrap script
```
Is that a problem with your server or with my zsh?

P.S. I guess it is with my zsh, using z4h.  I tried with sh and it worked.  Anyway, shouldn't it work with zsh?

**Comment by muesli** [comment]
You may have to disable z4h's SSH teleportation feature. Is this a fatal error it displays or just a warning?

**Comment by fredguth** [comment]
It seemed as a warning.
But turning off teleportation worked.  Thanks.
