### ISSUE TITLE
/.well-known/openid-configuration endpoint missing JWKS URI

### ISSUE THREAD

**Issue by rubiojr** [charmbracelet/charm#78]
The new `/.well-known/openid-configuration` endpoint recently introduced by https://github.com/charmbracelet/charm/pull/59 is no longer returning a valid `jwks_uri`:

```
[rubiojr@nano tavern] curl localhost:35354/.well-known/openid-configuration
{"issuer":"","authorization_endpoint":"","token_endpoint":"","jwks_uri":"http://:35354/v1/public/jwks","userinfo_endpoint":"","id_token_signing_alg_values_supported":null}
```

I think this is the result of https://github.com/charmbracelet/charm/pull/76 removing `localhost` as the default in the server configuration struct.

**Comment by aymanbagabas** [comment]
Thank you for reporting this bug! I've PR'd a fix for this, please let me know if it works.

**Comment by rubiojr** [comment]
> Thank you for reporting this bug! I've PR'd a fix for this, please let me know if it works.

Yup.
