### ISSUE TITLE
Backup-keys doesn't work

### ISSUE THREAD

**Issue by crile** [charmbracelet/charm#91]
Hi,

I try to backup my keys but after the import, I lose my files.

Steps to reproduce
1. I work with a localhost charm server `export CHARM_HOST=localhost`
2. Copy a file: `charm fs cp delta.md charm:/`
3. Check that the file is listed: `charm fs tree charm:/`
4. Backup: ` charm backup-keys`
5. Remove the keys: `rm -fr ~/.local/share/charm`
6. Listed the (new) user content: `charm fs tree charm:/`
7. Import the keys to retrieve my files: `charm import-keys charm-keys-backup.tar`
8. My file is not listed: `charm fs tree charm:/`

A simple `tar -czf` of the keys directory work fine.
I use ubuntu.

**Comment by bashbunni** [comment]
Was able to reproduce this issue. Another interesting finding was the user not being associated with the imported keys as well. It didn't bring over the previous username and in the "Manage Linked Keys" dialogue I didn't see the keys from backup. Also interesting was getting a warning that importing keys might overwrite existing keys in `~/.local/share/charm/localhost`, after having just deleted the `~/.local/share/charm/` directory (see screenshot)
<img width="626" alt="removed-charm-dir screenshot" src="https://user-images.githubusercontent.com/15822994/163657169-82acecd6-c7b4-417a-98a1-c70e5f1e525a.png">

Will look into this

**Comment by bashbunni** [comment]
Also noticed that the `charm backup-keys` creates an empty `tar` archive 🤔 definitely a bug. Thanks! We'll look into it 👍 

<img width="370" alt="empty-tar" src="https://user-images.githubusercontent.com/15822994/163658627-e5da99a1-c233-4ccd-822a-0f2ec92cbad7.png">

**Comment by bashbunni** [comment]
Merged 🥂
