### ISSUE TITLE
ui/keygen not generating keys for host

### ISSUE THREAD

**Issue by twpayne** [charmbracelet/charm#93]
Apologies if I've missed something obvious here. I was looking to test charm KV and ran the following commands:

```console
$ charm keygen

  ✔  Generated keys

$ charm id

  We were’t able to authenticate via SSH, which means
  there’s likely a problem with your key.

  You can generate SSH keys by running  charm keygen . You
  can also set the environment variable  CHARM_SSH_KEY_PATH
  to point to a specific private key, or use  -i specifify a
  location.
```

I expected `charm id` to report an identity associated with the keys I just created.

I tried this in a basic Docker container and got the same result:

```console
$ docker run -it ubuntu:latest /bin/bash
...

# apt update && apt install -y wget
...

# wget https://github.com/charmbracelet/charm/releases/download/v0.10.3/charm_0.10.3_linux_amd64.deb
...

# dpkg -i charm_0.10.3_linux_amd64.deb
Selecting previously unselected package charm.
(Reading database ... 4470 files and directories currently installed.)
Preparing to unpack charm_0.10.3_linux_amd64.deb ...
Unpacking charm (0.10.3) ...
Setting up charm (0.10.3) ...

# charm keygen

  ✔  Generated keys

# charm id

  We were’t able to authenticate via SSH, which means
  there’s likely a problem with your key.

  You can generate SSH keys by running  charm keygen . You
  can also set the environment variable  CHARM_SSH_KEY_PATH
  to point to a specific private key, or use  -i specifify a
  location.
```

I also tried running a local `charm` server, but got the same result (output from the same Docker container):

```console
# charm serve &
[1] 2609
2022/03/08 21:34:47 Opening SQLite db: data/db/charm_sqlite.db
2022/03/08 21:34:47 http://localhost:35354
2022/03/08 21:34:47 Starting SSH server on :35353
2022/03/08 21:34:47 Starting HTTP server on: :35354
2022/03/08 21:34:47 Starting HTTP health server on: :35356

# export CHARM_HOST=localhost

# charm id

  We were’t able to authenticate via SSH, which means
  there’s likely a problem with your key.

  You can generate SSH keys by running  charm keygen . You
  can also set the environment variable  CHARM_SSH_KEY_PATH
  to point to a specific private key, or use  -i specifify a
  location.
```

Is there something that I'm missing?

**Comment by bashbunni** [comment]
Just to confirm, the `charm serve` process isn't being suspended in the background right? Are you able to see anything when you have the server running, then run `charm`? There should be output after `charm serve` giving you updates on any activity on the server. 

Let me know and I'll be happy to dig in to this further!

**Comment by twpayne** [comment]
Thank you for the reply! I think the `charm serve` process is running. I tested this using the docker commands above (up to and including)`charm serve &` and I got the following output from using `wget` to connect to it:

```console
# wget -O - http://localhost:35354
--2022-03-17 00:41:55--  http://localhost:35354/
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:35354... connected.
HTTP request sent, awaiting response... 2022/03/17 00:41:55 <- GET / 127.0.0.1
2022/03/17 00:41:55 -> 400 Bad Request 29B 14.413µs
400 Bad Request
2022-03-17 00:41:55 ERROR 400: Bad Request.
```

The `400 Bad Request` response indicates that the charm server (or something else speaking HTTP on port 35354) is running, and I would expect such a 4xx response from the server given that the request body is empty.

**Comment by twpayne** [comment]
When I run `charm` I get the following output:

```
root@1a1cfd650090:/# charm

   Charm

  │ Username: (none set)
  │ Joined: 17 Mar 2022

  > Link a machine
    Manage linked keys
    Set Username
    Backup
    Exit

  j/k, ↑/↓: choose • enter: select
```

Exploring this TUI seems to indicate that things are working well, for example choosing `Managed linked keys` prints a key with the very recent timestamp (likely the key that I created in this temporary docker container). This would seem to narrow down the problem to be "charm is working correctly, but `charm id` isn't printing the output expected by the user".

**Comment by bashbunni** [comment]
Hmm, this is interesting... I was able to reproduce the "Bad Request" response from the server with the `wget` command in my docker container (followed the steps you outlined above) despite having no issue with `charm id`. I've also reached out to some of my teammates for ideas. Will keep you updated!

**Comment by stephaneeybert** [comment]
Sorry to be off topic here, but I was enticed to come on this thread from its title, as I'm too, unsure how to get started with charm.

In fact, it's a bit worse, I wonder what I could use charm for. I tried to understand the possible usages from its website but was left wondering.

Maybe there is some documentation or a simple wiki page ? Or better, a video showing us what good things we can do with it ?

**Comment by bashbunni** [comment]
Hey @stephaneeybert thank you so much for reaching out! We're working on building out the documentation and providing more context around our projects both in written and video formats. It's really helpful to hear your pain points, so thank you for sharing. I'll update you on this thread when we have added some documentation that makes it a bit more clear on what you can do with Charm and how you can get started with using it

**Comment by stephaneeybert** [comment]
@bashbunni What !? The one bashbunny I watched last week with TJ showing how to turn nvim into an IDE ? What a surprise !! Thank you for your kind and quick come back !
Stephane Eybert
